FROM python:3.12-slim

WORKDIR /app
COPY requirements.txt .
#cache파일은 저장하지 않음
RUN pip install --no-cache-dir -r requirements.txt
#현재 위치의 모든 플젝 내용을 /app 아래 복사
COPY . . 
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]